### ISSUE TITLE
Asynchronous I/O implementation of poll()

### ISSUE THREAD

**Issue by vmayoral** [ros2/ros2_embedded_nuttx#19]
https://github.com/ros2/ros2_embedded_nuttx/tree/lio_list will prototype this possibility.

**Comment by vmayoral** [comment]
At [this point](https://github.com/ros2/ros2_embedded_nuttx/commit/7a709c5206ce03f862eccbea51e7934c27a45008) it's not possible to debug the aio code using gdb. @nuttx is it necessary to include debugging flags somewhere? (the debugger says that the code is not available but the `.o` files are present under `libc/bin`).

Also, @nuttx you might like to take a look at 7467d7dafbcaa700600d526d66c95c316690a185 and 709d150cc7da63f5a3734eeb561e077a52642e61 which seem necessary to use the aio implementation.

**Comment by gregory-nutt** [comment]
@vmayoral "At this point it's not possible to debug the aio code using gdb. @nuttx is it necessary to include debugging flags somewhere? (the debugger says that the code is not available but the  .o  files are present under  libc/bin )."

You enable debug symbols in the Build Setup -> Debug Options -> Generate Debug Symbols option.

@vmayoral "Also, @nuttx you might like to take a look at  7467d7d  and  709d150  which seem necessary to use the aio implementation."

Yes, thanks.  Those are bugs.  I have no test case for the socket AIO operations so you are using completely untested logic with that.  I also found several closely related bugs.  See: http://sourceforge.net/p/nuttx/git/ci/91d6f23767cbd9cd8eabd1caeba75153013a94cc/

**Comment by vmayoral** [comment]
> You enable debug symbols in the Build Setup -> Debug Options -> Generate Debug Symbols option.

That did it. For some reason i though they were already enabled :/. Thanks!

> I have no test case for the socket AIO operations so you are using completely untested logic with that.

Quick tests with it doesn't look good. I will dedicate some time and try to make it work. It'll be great to have it working instead of 4 separate threads. This is giving me quite a headache: pointers jumping between the different SRAM sections and going to invalid regions of memory :(.

@nuttx one of the things worrying us is if the aio_read() calls will return to us the whole Ethernet package received from the file descriptor or only the payload. Did you implemented some header processing capabilities within AIO? We will need to whole package to obtain the endpoints, ports, etc.

**Comment by gregory-nutt** [comment]
@vmayoral "one of the things worrying us is if the aio_read() calls will return to us the whole Ethernet package received from the file descriptor or only the payload. Did you implemented some header processing capabilities within AIO? We will need to whole package to obtain the endpoints, ports, etc."

yes, I believe that is a problem.  aio_read() maps to recv() which is not useful with UDP packets.

**Comment by vmayoral** [comment]
Since this path doesn't seem feasible it'll be closed for now.
